-- From the table DEPOSIT perform the following queries:
use CSE_3B_422

-------------------- Part – A: --------------------

-- 1. Copy all records from DEPOSIT where AMOUNT > 3000 into HIGH_AMOUNT.
SELECT * INTO HIGH_AMOUNT
FROM BANK_DEPOSIT
WHERE BALANCE > 3000 ;

SELECT * FROM HIGH_AMOUNT


-- 2. Copy only CNAME and AMOUNT from DEPOSIT where BNAME = 'MAVDI' into MAVDI_CUSTOMERS.
SELECT CUSTOMER_NAME,BRANCH_NAME INTO MAVDI_CUSTOMERS
FROM BANK_DEPOSIT
WHERE BRANCH_NAME = 'MAVDI';

SELECT * FROM MAVDI_CUSTOMERS


-- 3. Copy records of DEPOSIT where ADATE > '2025-01-01' into RECENT_DEPOSITS.
-- SELECT ADATE INTO RECENT_DEPOSITS
-- FROM BANK_DEPOSIT
-- WHERE ADATE > '2025-01-01';

-- SELECT * FROM RECENT_DEPOSITS


-- 4. Copy distinct BNAME from DEPOSIT into BRANCH_LIST.
SELECT DISTINCT BRANCH_NAME 
INTO BRANCH_LIST
FROM BANK_DEPOSIT;

SELECT * FROM BRANCH_LIST

-- 5. Copy top 5 records from DEPOSIT into TOP_DEPOSITS.
SELECT TOP 5 * INTO TOP_DEPOSITS
FROM BANK_DEPOSIT;

SELECT * FROM TOP_DEPOSITS


-- 6. Copy records where AMOUNT between 2000 and 6000 into MID_RANGE.
SELECT BALANCE INTO MID_RANGE
FROM BANK_DEPOSIT
WHERE BALANCE >2000 AND BALANCE <6000;

SELECT * FROM MID_RANGE


-- 7. Copy distinct branch names from DEPOSIT into UNIQUE_BRANCH.
SELECT DISTINCT BRANCH_NAME INTO UNIQUE_BRANCH
FROM BANK_DEPOSIT;

SELECT * FROM UNIQUE_BRANCH


-- 8. Copy records with NULL branch into NO_BRANCH_ASSIGNED.
SELECT * INTO NO_BRANCH_ASSIGNED
FROM BANK_DEPOSIT
WHERE BRANCH_NAME IS NULL;

SELECT * FROM NO_BRANCH_ASSIGNED


-- 9. Copy all records and rename AMOUNT as BALANCE into DEPOSIT_COPY.
SELECT ANO,CUSTOMER_NAME,BRANCH_NAME AS BALANCE 
INTO DEPOSIT_COPY    
FROM BANK_DEPOSIT;

SELECT * FROM BANK_DEPOSIT


-- 10. Copy records where BNAME in ('MAVDI','BEDI') into SELECTED_BRANCH.
SELECT BRANCH_NAME INTO SELECTED_BRANCH
FROM BANK_DEPOSIT
WHERE BRANCH_NAME IN ('MAVDI','BEDI');

SELECT * FROM SELECTED_BRANCH


-------------------- Part – B: --------------------


-- 11. Create a new table STUDENT_BACKUP from STUDENT without copying any data.
SELECT * INTO STUDENT_BACKUP
FROM STUDENT
WHERE 1 = 0 ;

SELECT * FROM STUDENT_BACKUP
SELECT * FROM STUDENT

-- 12. Copy SNAME and CITY where BRANCH = 'COMPUTER' into CS_STUDENTS.
SELECT SNAME , CITY INTO CS_STUDENTS
FROM STUDENT
WHERE BRANCH = 'COMPUTER';

SELECT * FROM CS_STUDENTS


-- 13. Copy top 3 students based on SPI into TOPPER_LIST.
SELECT TOP 3 * INTO TOPPER_LIST
FROM STUDENT
ORDER BY SPI DESC;

SELECT * FROM TOPPER_LIST


-- 14. Copy distinct CITY from STUDENT into CITY_LIST.
SELECT DISTINCT CITY 
INTO CITY_LIST
FROM STUDENT;

SELECT * FROM CITY_LIST


-- 15. Copy records where STDID between 103 and 108 into MID_STUDENTS.
SELECT * INTO MID_STUDENTS
FROM STUDENT
WHERE STDID BETWEEN 103 AND 108;

SELECT * FROM MID_STUDENTS


-------------------- Part – C: --------------------


-- 16. Copy records with NULL branch into NULL_BRANCH_STUDENTS.
SELECT * INTO NULL_BRANCH_STUDENTS
FROM STUDENT
WHERE BRANCH IS NULL;

SELECT * FROM NULL_BRANCH_STUDENTS


-- 17. Copy all STUDENT records and rename SPI as PERFORMANCE into STUDENT_COPY.
SELECT STDID, NAME, BRANCH, CITY, SPI AS PERFORMANCE
INTO STUDENT_COPY
FROM STUDENT;

SELECT * FROM STUDENT_COPY


-- 18. Copy records where CITY in ('RAJKOT','SURAT') into CITY_WISE.
SELECT * INTO CITY_WISE
FROM STUDENT
WHERE CITY IN ('RAJKOT', 'SURAT');

SELECT * FROM CITY_WISE


-- 19. Copy students where BRANCH <> 'CIVIL' into NON_CIVIL_STUDENTS.
SELECT * INTO NON_CIVIL_STUDENTS
FROM STUDENT
WHERE BRANCH <> 'CIVIL';

SELECT * FROM NON_CIVIL_STUDENTS


-- 20. Copy selected columns (SNAME, CITY) from STUDENT table into a new table.
SELECT SNAME , CITY INTO NEW_TABLE_STUDENT
FROM STUDENT;

SELECT * FROM NEW_TABLE_STUDENT

